[tool.poetry]
name = "oversight"
version = "0.1.0"
description = ""
authors = [""]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.5"
pyserial = "^3.4"
minimalmodbus = "^0.7.0"
django = "^2.1"
cheroot = "^6.5"
requests = "^2.19"
cherrypy = "*"

[tool.poetry.dev-dependencies]
