---

- name: ensure python-apt
  shell: apt-get -y install python-apt creates=/usr/share/doc/python-apt

- name: common packages
  apt: pkg={{ item }}
  with_items:
    - python-pip
    - python-virtualenv
    - vim
    - git

- name: disable ssh root login with password
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin.*$" line="PermitRootLogin without-password"
  notify: restart ssh

- include: rbpi.yml
  when: "{{ ansible_ssh_user == 'pi' }}"
