---

- name: folder structure
  file: dest=/oversight/{{ item }} state=directory
  with_items:
    - config
    - logs
    - db
    - static

- name: install config file
  template: dest=/oversight/config/settings.py src=settings.py.j2

- name: install server wrapper
  copy: dest=/oversight/config/server.py src=server.py

- name: update pip
  pip: name=pip virtualenv=/oversight/venv state=latest

- name: oversight deps
  pip: name={{ item }} virtualenv=/oversight/venv
  with_items:
    - pyserial
    - MinimalModbus
    - https://www.djangoproject.com/download/1.7c2/tarball/
    - CherryPy

- name: update oversight
  git: repo=https://github.com/apollo13/oversight.git dest=/oversight/code update=yes

- name: collect static files
  django_manage:
    command: collectstatic
    app_path: /oversight/code
    settings: settings
    pythonpath: /oversight/config
    virtualenv: /oversight/venv

- name: migrate database
  django_manage:
    command: migrate
    app_path: /oversight/code
    settings: settings
    pythonpath: /oversight/config
    virtualenv: /oversight/venv

- name: install supervisor config file
  copy: dest=/etc/supervisor/conf.d/oversight.conf src=oversight.conf
  sudo_user: root
  register: supervisor_config

- name: reread supervisor config
  supervisorctl: state=present name="oversight:" server_url="unix:////var/run/supervisor.sock"
  sudo_user: root
  when: supervisor_config|changed

- name: restart oversight programs
  supervisorctl: state=restarted name="oversight:" server_url="unix:////var/run/supervisor.sock"
  sudo_user: root
