---
- name: Basic Configuration
  hosts: oversight
  remote_user: pi
  gather_facts: no
  sudo: true

  roles:
    - common

  tags:
    - bootstrap

- name: Oversight Bootstrap
  hosts: oversight
  remote_user: pi
  gather_facts: no
  sudo: true

  tasks:
    - user: name=oversight home=/oversight groups=dialout

  roles:
    - nginx
    - supervisor

  tags:
    - bootstrap

- name: Oversight Deployment
  hosts: oversight
  remote_user: pi
  gather_facts: no
  sudo: true
  sudo_user: oversight

  roles:
    - oversight

  tags:
    - deployment
