# Generated by Django 2.1.1 on 2018-09-12 10:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('api_endpoint', models.SlugField(unique=True)),
                ('unit', models.CharField(max_length=255)),
                ('sensor_class', models.CharField(max_length=255)),
                ('params', models.TextField()),
                ('log_plot', models.BooleanField(default=False)),
                ('logging_enabled', models.BooleanField(default=True)),
                ('alarm_below', models.CharField(blank=True, max_length=255)),
                ('alarm_above', models.CharField(blank=True, max_length=255)),
                ('alarm_acked', models.BooleanField(default=True)),
                ('current_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='oversight.LogEntry')),
            ],
        ),
        migrations.AddField(
            model_name='logentry',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oversight.Sensor'),
        ),
        migrations.AlterIndexTogether(
            name='logentry',
            index_together={('sensor', 'datetime')},
        ),
    ]
